# Generated by Django 2.2 on 2020-11-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_auto_20191230_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('post_collected', models.ManyToManyField(blank=True, related_name='all_users_collected', to='blog.Post')),
                ('post_liked', models.ManyToManyField(blank=True, related_name='all_users_liked', to='blog.Post')),
            ],
        ),
    ]
